# Generated by Django 3.2 on 2024-11-17 16:47

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unique_id', models.CharField(max_length=100, unique=True)),
                ('access_count', models.IntegerField(default=0)),
            ],
        ),
    ]
